[build]
  publish = "dist"
  command = "npm run build"

[functions]
directory = "src/pages/api"

[build.processing.html]
  pretty_urls = false
[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
